// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChciUrpW8Dx3u29AA0ErlqIEcmp4qkbA0',
    appId: '1:200093430572:web:355f4150c5809664063289',
    messagingSenderId: '200093430572',
    projectId: 'realtime-line-chart',
    authDomain: 'realtime-line-chart.firebaseapp.com',
    storageBucket: 'realtime-line-chart.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrItz9Zl5zJr1boC9XkXmpvllgmvjSBRc',
    appId: '1:200093430572:android:6683c782fe6a650b063289',
    messagingSenderId: '200093430572',
    projectId: 'realtime-line-chart',
    storageBucket: 'realtime-line-chart.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhS_IC9vkMq-55cPO4zuqBg_VPIA6lVwA',
    appId: '1:200093430572:ios:8b0792a05d770cd4063289',
    messagingSenderId: '200093430572',
    projectId: 'realtime-line-chart',
    storageBucket: 'realtime-line-chart.appspot.com',
    iosBundleId: 'com.example.realtimeLineChart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhS_IC9vkMq-55cPO4zuqBg_VPIA6lVwA',
    appId: '1:200093430572:ios:8b0792a05d770cd4063289',
    messagingSenderId: '200093430572',
    projectId: 'realtime-line-chart',
    storageBucket: 'realtime-line-chart.appspot.com',
    iosBundleId: 'com.example.realtimeLineChart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChciUrpW8Dx3u29AA0ErlqIEcmp4qkbA0',
    appId: '1:200093430572:web:fc509c2a133d0771063289',
    messagingSenderId: '200093430572',
    projectId: 'realtime-line-chart',
    authDomain: 'realtime-line-chart.firebaseapp.com',
    storageBucket: 'realtime-line-chart.appspot.com',
  );
}
